extract_job_description_data:
  description: >
    Perform a comprehensive analysis of the provided job description to extract and categorize:
    
    1. Required Technical Skills:
       - Programming languages, frameworks, and tools
       - Software and platform expertise
       - Industry-specific technical requirements
    
    2. Required Soft Skills:
       - Communication, leadership, teamwork abilities
       - Problem-solving and analytical skills
       - Adaptability and learning capabilities
    
    3. Experience Requirements:
       - Years of experience needed
       - Specific industry or domain experience
       - Type of projects or responsibilities
    
    4. Educational Qualifications:
       - Degree requirements
       - Preferred fields of study
       - Certifications or additional qualifications
    
    5. Job Responsibilities:
       - Primary duties and responsibilities
       - Key performance indicators
       - Team and project management expectations
    
    6. Company Culture and Values:
       - Work environment preferences
       - Cultural fit indicators
       - Growth and development opportunities
    
    Prioritize requirements based on their importance (must-have vs nice-to-have).
    
    Parameters:
    - job_description: {job_description}
  
  expected_output: >
    A detailed analysis report containing:
    1. Categorized list of required technical skills with priority levels
    2. Essential soft skills and behavioral competencies
    3. Experience requirements breakdown with minimum and preferred levels
    4. Educational and certification requirements
    5. Key job responsibilities and performance expectations
    6. Company culture and work environment insights
    7. Priority matrix indicating must-have vs preferred qualifications
    8. Industry context and competitive landscape insights
    
    The analysis should provide clear guidance for resume optimization and highlight
    the most critical elements for job application success.

tune_resume_for_job:
  description: >
    Using the retrieved resume information and job description analysis, create an optimized
    version of the resume that maximally aligns with the job requirements while maintaining
    authenticity and truthfulness. Perform the following optimizations:
    
    1. Content Alignment:
       - Highlight relevant experiences that match job requirements
       - Reframe existing skills and experiences using job-relevant terminology
       - Prioritize sections and bullet points based on job importance
    
    2. Skills Optimization:
       - Emphasize technical skills that match job requirements
       - Add relevant keywords for ATS optimization
       - Group and present skills in order of relevance to the position
    
    3. Experience Enhancement:
       - Rewrite job descriptions to highlight relevant achievements
       - Quantify accomplishments where possible
       - Use action verbs that resonate with the job description
    
    4. Structure and Format:
       - Organize sections to prioritize most relevant information
       - Ensure professional formatting and readability
       - Optimize for both ATS scanning and human review
    
    5. Keyword Optimization:
       - Integrate important keywords from job description naturally
       - Maintain keyword density for ATS compatibility
       - Ensure context-appropriate usage of industry terminology
    
    6. Gap Analysis and Recommendations:
       - Identify any gaps between resume and job requirements
       - Suggest areas for skill development or additional experience
       - Provide recommendations for strengthening the application
    
    IMPORTANT: All modifications must be truthful and based on existing resume content.
    Do not fabricate experiences, skills, or qualifications.

    Parameters:
    - resume: {resume}

  expected_output: >
    A comprehensive resume tuning package containing:
    1. Optimized resume version with enhanced alignment to job requirements
    2. Side-by-side comparison showing key changes made
    3. ATS optimization report with keyword analysis
    4. Gap analysis identifying areas where the candidate may fall short
    5. Improvement recommendations for strengthening future applications
    6. Cover letter talking points that complement the optimized resume
    7. Interview preparation notes highlighting key strengths to emphasize
    
    The optimized resume should:
    - Maintain 100% truthfulness and authenticity
    - Maximize relevance to the specific job opportunity
    - Be ATS-friendly while remaining human-readable
    - Clearly demonstrate value proposition to potential employers
    - Include strategic placement of keywords and phrases from the job description

    